### ISSUE TITLE
options.validator and options.keyValidator shouldn't be mendatory

### ISSUE THREAD

**Issue by Cl00e9ment** [timtnleeProject/skeletons#10]
When using Skeletons as ES module, `options.validator` and `options.keyValidator` are required because of a typo in `index.d.ts`.

**Comment by Cl00e9ment** [comment]
Issue fixed, all that left is to publish the new version to NPM registry.

**Comment by timtnleeProject** [comment]
Hi, @Cl00e9ment 
I've already published `v0.2.2`
I'm thinking about adding you to the NPM package collaborator so you can publish the package directly :)
Would you mind give me your NPM account to become the collaborator?

**Comment by Cl00e9ment** [comment]
Il would be great yes, [here](https://www.npmjs.com/~cl00e9ment) his my profil.
