### ISSUE TITLE
Can't call validate because of its declaration in index.d.ts

### ISSUE THREAD

**Issue by Cl00e9ment** [timtnleeProject/skeletons#4]
I tested this simple example present in the documentation:

```typescript
import 'Skeletons' from skeletons;
new Skeletons(Number).validate(5);
```

Unfortunately, I got an error because `validate` expects no argument. Indeed, in the `index.d.ts` file, `validate` is declared as follow:

```typescript
 validate ():any
```

Shouldn't be something like that instead?

```typescript
validate(data: any, opt?: object): boolean
```

This module really meets my needs. I hope that this will be fixed soon.
Thank you.

**Comment by timtnleeProject** [comment]
Hi @Cl00e9ment ,
thanks for the issue, I've update the package to `v0.0.1`
if you have any fix you can also send Pr directly,
thx!

**Comment by Cl00e9ment** [comment]
Thanks, it works.
I will probably send pull requests in the future to add some features.
