### ISSUE TITLE
Got undefined when importing Skeletons

### ISSUE THREAD

**Issue by Cl00e9ment** [timtnleeProject/skeletons#5]
When I try to import Skeletons I get undefined:

```typescript
import Skeletons from 'skeletons';
console.log(Skeletons);
```
> undefined

However, this is what I get when I import everything:

```typescript
import * as Skeletons from 'skeletons';
console.log(Skeletons);
```
>[Function: Skeletons] {
>   _version_: '0.1.0',
>   String: [Function],
>   Array: [Function],
>   Boolean: [Function],
>   Number: [Function],
>   Object: [Function],
>   MapObject: [Function],
>   Function: [Function],
>   Symbol: [Function],
>   Null: [Function],
>   Any: [Function],
>   Types: [Function],
>   Warnings: [Function],
>   typeof: [Function],
>   getKeyStr: [Function],
>   setDefault: [Function],
>   expectType: [Function]
> }

I can't use this last syntax because this isn't an intended behaviour (it's inconsistent with `index.d.ts`).

I tried to fix that myself, but I'm not familiar with the tools that you used.

Thanks.

**Comment by Cl00e9ment** [comment]
I found where the bug come from. It come from the [add-module-exports Babel plugin](https://www.npmjs.com/package/babel-plugin-add-module-exports), see [this issue](https://github.com/59naga/babel-plugin-add-module-exports/issues/12).

## Explanation

When Babel transpile Skeletons, this

```javascript
export default Skeletons
```

become this:

```javascript
var _default = Skeletons;
exports["default"] = _default;
module.exports = exports.default;
```

The last line cancels `exports["default"] = _default` because you can't use both `exports.default` and `module.exports` (see [this anwser](https://stackoverflow.com/a/54900077/9515617)). The last line also reset the `__esModule` flag.

So, let Foo, an ES module that use Skeletons:

```javascript
import Skeletons from 'skeletons';
```

If Foo is transpiled with Babel, the generated CommonJS code will check if Skeletons is an ES module and it's not because the `__esModule` flag has been reset. Thus, it will works.

If Foo is transpiled with tsc (TypeScript Compile), the generated CommonJS code will infers that Skeletons is an ES module because we used the `import` statement. tsc does not verify the `__esModule` flag because it's a Babel flag. Thus it will not work because `exports.default` equals `undefined`.

## Workaround

Simply add the `addDefaultProperty` property for the `add-module-exports` plugins:

```json
{
    "presets": ["@babel/preset-env"],
    "plugins": [
        [
            "add-module-exports",
            {
                "addDefaultProperty": true
            }
        ]
    ]
}
```

**Comment by Cl00e9ment** [comment]
Since this bug has been fixed in the last commit, will you soon publish the new version on NPM?
Thanks.

**Comment by timtnleeProject** [comment]
Thanks @Cl00e9ment ,
The new version has published
